version: '3'
services:
    zoo-app:
      build: .
      container_name: zoo-app
      ports:
        - '8080:8080'
      depends_on:
        - zoo_db
      environment:
        DB_HOST: host.docker.internal
        ELASTIC_HOST: host.docker.internal
        SPRING_PROFILES_ACTIVE: dev

    zoo_db:
      image: mariadb:11.0
      container_name: zoo_db
      environment:
        MARIADB_USER: root
        MARIADB_ROOT_PASSWORD: root
        MARIADB_DATABASE: zoo
      ports:
        - '3306:3306'

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
      environment:
        - bootstrap.memory_lock=true
        - ELASTIC_PASSWORD=changeme
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        - cluster.routing.allocation.disk.threshold_enabled=false
        - xpack.security.enabled=false
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - 9200:9200
      networks: ['stack']

    kibana:
      image: docker.elastic.co/kibana/kibana:8.8.1
      links:
        - elasticsearch
      ports:
        - 5601:5601
      networks: ['stack']
      depends_on:
        - elasticsearch

networks:
  stack: {}

