version: '3'
services:
    zoo-app:
      build: .
      container_name: zoo-app
      ports:
        - '8080:8080'
      depends_on:
        - zoo_db
      environment:
        DB_HOST: host.docker.internal
        SPRING_PROFILES_ACTIVE: dev

    zoo_db:
      image: mariadb:11.0
      container_name: zoo_db
      environment:
        MARIADB_USER: root
        MARIADB_ROOT_PASSWORD: root
        MARIADB_DATABASE: zoo
      ports:
        - '3306:3306'

